<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AD-BOTON PERSONAL</name>
   <tag></tag>
   <elementGuidId>812272b3-b451-40fa-a97a-84e7b826de2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login-box-parent > a.btn.btn-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login-box-parent']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7c2f882b-3038-4c89-81dd-161b92c6f396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#personal</value>
      <webElementGuid>1d185cd3-528e-4e83-9ede-82ac35a3ae22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>c1b28fb2-f58e-44cf-82a4-0062012c560e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>ac921f9f-dae7-4aea-952d-3c762c2ca024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Personal
        </value>
      <webElementGuid>02fed132-2f6e-46aa-90e3-b289ccfdef36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-box-parent&quot;)/a[@class=&quot;btn btn-primary&quot;]</value>
      <webElementGuid>97ced7bc-6de3-4315-b37d-e876821b8e25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-box-parent']/a</value>
      <webElementGuid>fb2e477c-5fc2-42bf-b9b3-1ec55519ac67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regresar a Bancanet'])[1]/following::a[1]</value>
      <webElementGuid>96ee1656-1190-4b0d-807f-0bee28113831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar Pago'])[2]/following::a[2]</value>
      <webElementGuid>f5cb7f84-2bbd-4f9f-b3ac-2167c995f1e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Empresarial'])[1]/preceding::a[1]</value>
      <webElementGuid>8d7f8a28-2cff-4644-9912-616ce9923499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#personal')]</value>
      <webElementGuid>cabbf36c-6a91-430f-9832-3bc3bcb0dc7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[25]/div/div/div/a</value>
      <webElementGuid>e757b512-07cf-41ea-8369-1ee68abb7dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#personal' and (text() = '
            Personal
        ' or . = '
            Personal
        ')]</value>
      <webElementGuid>24282b19-4875-49b6-9e7b-8c63f9d5f47a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
